name = Twosides Layout
description = Layout for Internal Pages
template = twosides-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[slider] = Slider Area
regions[highlighted] = Highlighted
regions[help] = Help
regions[sidebar_first] = First Sidebar
regions[content] = Content
regions[footer] = Footer

; ========================================
; Stylesheets
; ========================================

stylesheets[all][] = css/layouts/twosides/twosides.layout.styles.css
stylesheets[all][] = css/layouts/twosides/twosides.layout.no-query.css
