name = Home Layout
description = Layout for front-page theme
template = home-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[slider] = Slider Area
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[content_down]  = Content Down
regions[footer] = Footer

; ========================================
; Stylesheets
; ========================================

stylesheets[all][] = css/layouts/home/home.layout.styles.css
stylesheets[all][] = css/layouts/home/home.layout.no-query.css